# non-overridable settings, see
# https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll
safe: true
lsi: false

# custom configuration
timezone: Europe/Prague
encoding: utf-8
markdown: redcarpet
baseurl: /musing
